export const signUpController = async (req, res) => {
  try {
  } catch (err) {
    console.log('signUpController - error= ', err);
    res.status(404).send(err);
  }
};

export const loginController = async (req, res) => {
  try {
  } catch (err) {
    console.log('loginController - error= ', err);
    res.status(404).send(err);
  }
};
